

<div class="sidebar">
        <h2>Navigation Panel</h2>
        <ul>
            <li><a href="index.php"><span class="fa fa-home"> </span> Home-Index</a></li>
            <li><a href="topic.php"><span class="fa fa-info-circle"></span> Topic</a></li>
            <li><a href="quiz.php"><span class="fa fa-puzzle-piece"> </span> Quiz</a></li>
            <li><a href="enhancements.html"><span class="fa fa-lightbulb-o"> </span> Enhancements</a></li>
            <li><a href="enhancements2.html"><span class="fa fa-star-o"> </span> Enhancements part 2</a></li>
            <li><a href="login.php"><span class="fa fa-search"> </span>Quiz Supervisor</a></li>
            <li><a href="phpenhancements.php"><span class="fa fa-star"> </span>PHP Enchancements</a></li>

            
        </ul> 
        <div class="Reference">
          <a href="https://www.swinburne.edu.au/"><span class="fa fa-university"></span></a>
          <a href="https://www.codecademy.com/"><span class="fa fa-code" ></span></a>
          <a href="https://github.com/"><span class="fa fa-share-alt"></span></a>
      </div>
    </div>
	
	